version: "2.1"
services:
  mikhmon:
    image: animegasan/extraordinary-cbt:latest
    container_name: extraordinary-cbt
    ports:
      - 8080:80
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    restart: unless-stopped
